### ISSUE TITLE
RVPROXY for VRS requires additional params

### ISSUE THREAD

**Issue by rikgale** [kx1t/docker-reversewebproxy#1]
Heya.

Been using this container in my stack. I have got all the sites to work through this. PF / PA / Readsb /graphs etc. IT's great! Tried adding VRS to this and really struggled to get it all to work. After much research I manually altered in the location.conf file

Changed 

```
location /vrs/ {
    proxy_pass http://192.168.1.32:8090/VirtualRadar/;
}
```

to

```
location /vrs/ {
    proxy_pass http://192.168.1.32:8090/VirtualRadar/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
}
```

Would it be possible to add these additional parameters in as you have done similar for Acarshub. Don't want any other poor person to travel the journey I have this evening trying to get access via the reverse proxy. IF you do update then also in the instructions you will need to get the user to to change VRS Options -> Wedsite -> Website Customisation -> Proxy Type = Reverse.

I should probably add - if of any relevance that I am running my VRS outside of the container stack not in a container.

Many thanks
Richard aka rikgale

**Comment by kx1t** [comment]
Hi Richard,

Thanks for the enhancement request. 

I had already pulled several of these parameters into the standard header-set for all `proxy_pass` entries, but you identified a few extra/new ones. I've added those as well in `default`, see here: https://github.com/kx1t/docker-reversewebproxy/commit/d281d40c3465cf3deeca92e837ebb0ea1d785822

A new build was automatically created and pushed -- could you please pull the latest container, test it, and let me know if it fixes the issue?

**Comment by kx1t** [comment]
Glad to see :)
